default:
  image: julia:1.3

stages:
  - test
  - pages

before_script:
    - >
        export JULIA_NUM_THREADS=$(( $(nproc) > 1 ? $(nproc) : 2 ));
        echo $(nproc) processors available, testing with $JULIA_NUM_THREADS threads

test:
  script:
    - julia --project -e "using Pkg; Pkg.instantiate()"
    - julia --project test/runtests.jl

pages:
  script:
    - cd docs
    - julia --project -e "using Pkg; Pkg.instantiate()"
    - julia --project make.jl
    - mv build/* public/
  artifacts:
    paths:
      - public
