name = "Actors"
uuid = "18269d71-cc38-4e02-b8c8-1db30113a6dd"
authors = ["Richard Palethorpe <richiejp@f-m.fm>"]
version = "0.0.1"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
