name = "Actors"
uuid = "18269d71-cc38-4e02-b8c8-1db30113a6dd"
authors = ["Richard Palethorpe <richiejp@f-m.fm>"]
version = "0.4.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[targets]
test = ["Test", "Random"]
